.include "sound/voicegroups/dummy.inc"

@ drumsets
.include "sound/voicegroups/drumsets/rs.inc"
.include "sound/voicegroups/drumsets/frlg.inc"
.include "sound/voicegroups/drumsets/emerald_1.inc"
.include "sound/voicegroups/drumsets/emerald_2.inc"

@ key splits
.include "sound/voicegroups/keysplits/piano.inc"
.include "sound/voicegroups/keysplits/strings.inc"
.include "sound/voicegroups/keysplits/trumpet.inc"
.include "sound/voicegroups/unused.inc"
.include "sound/voicegroups/keysplits/tuba.inc"
.include "sound/voicegroups/keysplits/french_horn.inc"

.include "sound/voicegroups/route110.inc"
.include "sound/voicegroups/route101.inc"
.include "sound/voicegroups/fanfare.inc"
.include "sound/voicegroups/gym.inc"
.include "sound/voicegroups/route120.inc"
.include "sound/voicegroups/petalburg.inc"
.include "sound/voicegroups/drumsets/petalburg.inc"
.include "sound/voicegroups/surf.inc"
.include "sound/voicegroups/petalburg_woods.inc"
.include "sound/voicegroups/oldale.inc"
.include "sound/voicegroups/lilycove_museum.inc"
.include "sound/voicegroups/route122.inc"
.include "sound/voicegroups/drumsets/route101.inc"
.include "sound/voicegroups/oceanic_museum.inc"
.include "sound/voicegroups/victory_gym_leader.inc"
.include "sound/voicegroups/victory_wild.inc"
.include "sound/voicegroups/evolution.inc"
.include "sound/voicegroups/encounter_girl.inc"
.include "sound/voicegroups/encounter_male.inc"
.include "sound/voicegroups/victory_league.inc"
.include "sound/voicegroups/abandoned_ship.inc"
.include "sound/voicegroups/drumsets/route110.inc"
.include "sound/voicegroups/fortree.inc"
.include "sound/voicegroups/birch_lab.inc"
.include "sound/voicegroups/littleroot_test.inc"
.include "sound/voicegroups/b_tower_rs.inc"
.include "sound/voicegroups/encounter_swimmer.inc"
.include "sound/voicegroups/cave_of_origin.inc"
.include "sound/voicegroups/roulette.inc"
.include "sound/voicegroups/link_contest_p1.inc"
.include "sound/voicegroups/link_contest_p2.inc"
.include "sound/voicegroups/link_contest_p3.inc"
.include "sound/voicegroups/link_contest_p4.inc"
.include "sound/voicegroups/encounter_rich.inc"
.include "sound/voicegroups/verdanturf.inc"
.include "sound/voicegroups/rustboro.inc"
.include "sound/voicegroups/poke_center.inc"
.include "sound/voicegroups/route104.inc"
.include "sound/voicegroups/route119.inc"
.include "sound/voicegroups/cycling.inc"
.include "sound/voicegroups/poke_mart.inc"
.include "sound/voicegroups/littleroot.inc"
.include "sound/voicegroups/mt_chimney.inc"
.include "sound/voicegroups/encounter_female.inc"
.include "sound/voicegroups/lilycove.inc"
.include "sound/voicegroups/route111.inc"
.include "sound/voicegroups/help.inc"
.include "sound/voicegroups/underwater.inc"
.include "sound/voicegroups/victory_trainer.inc"
.include "sound/voicegroups/title.inc"
.include "sound/voicegroups/intro.inc"
.include "sound/voicegroups/encounter_may.inc"
.include "sound/voicegroups/encounter_intense.inc"
.include "sound/voicegroups/encounter_cool.inc"
.include "sound/voicegroups/route113.inc"
.include "sound/voicegroups/encounter_aqua.inc"
.include "sound/voicegroups/follow_me.inc"
.include "sound/voicegroups/encounter_brendan.inc"
.include "sound/voicegroups/ever_grande.inc"
.include "sound/voicegroups/encounter_suspicious.inc"
.include "sound/voicegroups/victory_aqua_magma.inc"
.include "sound/voicegroups/cable_car.inc"
.include "sound/voicegroups/game_corner.inc"
.include "sound/voicegroups/dewford.inc"
.include "sound/voicegroups/safari_zone.inc"
.include "sound/voicegroups/victory_road.inc"
.include "sound/voicegroups/aqua_magma_hideout.inc"
.include "sound/voicegroups/sailing.inc"
.include "sound/voicegroups/mt_pyre.inc"
.include "sound/voicegroups/slateport.inc"
.include "sound/voicegroups/mt_pyre_exterior.inc"
.include "sound/voicegroups/school.inc"
.include "sound/voicegroups/hall_of_fame.inc"
.include "sound/voicegroups/fallarbor.inc"
.include "sound/voicegroups/sealed_chamber.inc"
.include "sound/voicegroups/contest_winner.inc"
.include "sound/voicegroups/contest.inc"
.include "sound/voicegroups/encounter_magma.inc"
.include "sound/voicegroups/intro_battle.inc"
.include "sound/voicegroups/abnormal_weather.inc"
.include "sound/voicegroups/weather_groudon.inc"
.include "sound/voicegroups/sootopolis.inc"
.include "sound/voicegroups/contest_results.inc"
.include "sound/voicegroups/hall_of_fame_room.inc"
.include "sound/voicegroups/trick_house.inc"
.include "sound/voicegroups/encounter_twins.inc"
.include "sound/voicegroups/encounter_elite_four.inc"
.include "sound/voicegroups/encounter_hiker.inc"
.include "sound/voicegroups/contest_lobby.inc"
.include "sound/voicegroups/encounter_interviewer.inc"
.include "sound/voicegroups/encounter_champion.inc"
.include "sound/voicegroups/credits.inc"
.include "sound/voicegroups/end.inc"
.include "sound/voicegroups/b_frontier.inc"
.include "sound/voicegroups/b_arena.inc"
.include "sound/voicegroups/register_match_call.inc"
.include "sound/voicegroups/b_pyramid.inc"
.include "sound/voicegroups/b_pyramid_top.inc"
.include "sound/voicegroups/b_palace.inc"
.include "sound/voicegroups/rayquaza_appears.inc"
.include "sound/voicegroups/b_tower.inc"
.include "sound/voicegroups/b_dome.inc"
.include "sound/voicegroups/b_pike.inc"
.include "sound/voicegroups/b_factory.inc"
.include "sound/voicegroups/vs_rayquaza.inc"
.include "sound/voicegroups/vs_frontier_brain.inc"
.include "sound/voicegroups/vs_mew.inc"
.include "sound/voicegroups/vs_wild.inc"
.include "sound/voicegroups/vs_aqua_magma.inc"
.include "sound/voicegroups/vs_trainer.inc"
.include "sound/voicegroups/vs_gym_leader.inc"
.include "sound/voicegroups/vs_champion.inc"
.include "sound/voicegroups/vs_regi.inc"
.include "sound/voicegroups/vs_kyogre_groudon.inc" @ duplicate of vs_rayquaza
.include "sound/voicegroups/vs_rival.inc"
.include "sound/voicegroups/vs_elite_four.inc"
.include "sound/voicegroups/vs_aqua_magma_leader.inc"
.include "sound/voicegroups/rs_sfx_1.inc"
.include "sound/voicegroups/rs_sfx_2.inc"
.include "sound/cry_tables.inc"
.include "sound/voicegroups/frlg_sfx.inc"
.include "sound/voicegroups/bard.inc"
.include "sound/voicegroups/unused_2.inc" @ used by unused GSC radio tower takeover test track in RS

@ FRLG
.include "sound/voicegroups/rg_follow_me.inc"
.include "sound/voicegroups/rg_game_corner.inc"
.include "sound/voicegroups/rg_rocket_hideout.inc"
.include "sound/voicegroups/rg_gym.inc"
.include "sound/voicegroups/rg_jigglypuff.inc"
.include "sound/voicegroups/rg_intro_fight.inc"
.include "sound/voicegroups/rg_title.inc"
.include "sound/voicegroups/rg_cinnabar.inc"
.include "sound/voicegroups/rg_lavender.inc"
.include "sound/voicegroups/rg_heal.inc"
.include "sound/voicegroups/rg_cycling.inc"
.include "sound/voicegroups/rg_encounter_rocket.inc"
.include "sound/voicegroups/rg_encounter_girl.inc"
.include "sound/voicegroups/rg_encounter_boy.inc"
.include "sound/voicegroups/rg_hall_of_fame.inc"
.include "sound/voicegroups/rg_viridian_forest.inc"
.include "sound/voicegroups/rg_mt_moon.inc"
.include "sound/voicegroups/rg_poke_mansion.inc"
.include "sound/voicegroups/rg_credits.inc"
.include "sound/voicegroups/rg_route1.inc"
.include "sound/voicegroups/rg_route24.inc"
.include "sound/voicegroups/rg_route3.inc"
.include "sound/voicegroups/rg_route11.inc"
.include "sound/voicegroups/rg_victory_road.inc"
.include "sound/voicegroups/rg_vs_gym_leader.inc"
.include "sound/voicegroups/rg_vs_trainer.inc"
.include "sound/voicegroups/rg_vs_wild.inc"
.include "sound/voicegroups/rg_vs_champion.inc"
.include "sound/voicegroups/rg_pallet.inc"
.include "sound/voicegroups/rg_oak_lab.inc"
.include "sound/voicegroups/rg_oak.inc"
.include "sound/voicegroups/rg_poke_center.inc"
.include "sound/voicegroups/rg_ss_anne.inc"
.include "sound/voicegroups/rg_surf.inc"
.include "sound/voicegroups/rg_poke_tower.inc"
.include "sound/voicegroups/rg_silph.inc"
.include "sound/voicegroups/rg_fuchsia.inc"
.include "sound/voicegroups/rg_celadon.inc"
.include "sound/voicegroups/rg_victory_trainer.inc"
.include "sound/voicegroups/rg_victory_wild.inc"
.include "sound/voicegroups/rg_victory_gym_leader.inc"
.include "sound/voicegroups/rg_vermillion.inc"
.include "sound/voicegroups/rg_pewter.inc"
.include "sound/voicegroups/rg_encounter_rival.inc"
.include "sound/voicegroups/rg_unused.inc"
.include "sound/voicegroups/rg_unused_2.inc"
.include "sound/voicegroups/rg_dex_rating.inc"
.include "sound/voicegroups/drumsets/frlg_fanfare_2.inc"
.include "sound/voicegroups/drumsets/frlg_fanfare_1.inc"
.include "sound/voicegroups/rg_obtain_key_item.inc"
.include "sound/voicegroups/rg_caught_intro.inc"
.include "sound/voicegroups/rg_photo.inc"
.include "sound/voicegroups/rg_game_freak.inc"
.include "sound/voicegroups/rg_new_game.inc"
.include "sound/voicegroups/rg_mystery_gift.inc"
.include "sound/voicegroups/rg_encounter_deoxys.inc"
.include "sound/voicegroups/rg_vs_deoxys.inc"
.include "sound/voicegroups/rg_teachy_tv_menu.inc"
.include "sound/voicegroups/rg_sevii_route.inc"
.include "sound/voicegroups/rg_sevii_45.inc"
.include "sound/voicegroups/rg_sevii_67.inc"
.include "sound/voicegroups/drumsets/rg_credits.inc"

	.align 2
voicegroup191:: @ DPPt main
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16
	voice_keysplit_all voicegroup192				 @ drums 1
	voice_keysplit voicegroup195, KeySplitTable6     @ piano
	voice_keysplit voicegroup196, KeySplitTable7     @ piano low
	voice_keysplit voicegroup197, KeySplitTable8     @ ep 1
	voice_keysplit voicegroup198, KeySplitTable9     @ ep 2
	voice_keysplit_all voicegroup193				 @ drums 2
	voice_keysplit voicegroup199, KeySplitTable10    @ clavi
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 42, 0, 57, 192
	voice_directsound 60, 0, DirectSoundWaveData_dp_glocken_c6_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 205
	voice_keysplit voicegroup200, KeySplitTable11    @ vibraphone
	voice_keysplit voicegroup201, KeySplitTable12    @ marimba
	voice_keysplit voicegroup202, KeySplitTable13    @ xylophone
	voice_keysplit voicegroup203, KeySplitTable14    @ tubular bell
	voice_keysplit voicegroup204, KeySplitTable15    @ trinity piano
	voice_keysplit_all voicegroup194				 @ synth kick + snare
	voice_keysplit voicegroup205, KeySplitTable16    @ rotary organ
	voice_keysplit voicegroup206, KeySplitTable17    @ straight organ
	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 175, 235, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 200, 255, 171
	voice_keysplit voicegroup207, KeySplitTable18    @ accordion
	voice_directsound 60, 0, DirectSoundWaveData_dp_harmonica_c3_16, 67, 247, 191, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_fretnoise60, 255, 0, 255, 16
	voice_keysplit voicegroup208, KeySplitTable19    @ acoustic guitar
	voice_directsound 60, 0, DirectSoundWaveData_dp_bluesgt_a2_16, 255, 255, 227, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_eternaguitar36, 255, 253, 159, 208
	voice_keysplit voicegroup209, KeySplitTable20    @ clean guitar
	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32
	voice_keysplit voicegroup210, KeySplitTable21    @ distortion guitar 1
	voice_keysplit voicegroup211, KeySplitTable22    @ power guitar
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0
	voice_keysplit voicegroup212, KeySplitTable23    @ upright bass 1
	voice_directsound 60, 0, DirectSoundWaveData_dp_sting_bass_e1_16, 255, 251, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_pickbass_e1_16, 255, 251, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_fretlessbass_d1_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_g1_16, 255, 0, 255, 222
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 42, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 222
	voice_keysplit voicegroup213, KeySplitTable24    @ violin
	voice_directsound 60, 0, DirectSoundWaveData_dp_oct_g3_16, 255, 235, 255, 212
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 252, 0, 96
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 37, 244, 155, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_explosion, 37, 255, 0, 246
	voice_keysplit voicegroup214, KeySplitTable25    @ pizzicato
	voice_keysplit voicegroup215, KeySplitTable26    @ harp
	voice_keysplit voicegroup216, KeySplitTable27    @ timpani 1
	voice_keysplit voicegroup217, KeySplitTable28    @ strings
	voice_directsound 60, 0, DirectSoundWaveData_dp_octlow_cs2_16, 255, 200, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_octlowbra_b2_16, 255, 200, 255, 226
	voice_keysplit voicegroup218, KeySplitTable27    @ timpani 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 250, 0, 220
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 250, 0, 171 @ shift up by 1 octave
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 150, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_octhit_c2_16, 255, 200, 255, 222
	voice_keysplit voicegroup219, KeySplitTable29    @ trumpets 1
	voice_keysplit voicegroup220, KeySplitTable30    @ trombone
	voice_keysplit voicegroup221, KeySplitTable31    @ tuba
	voice_keysplit voicegroup222, KeySplitTable29    @ trumpets 2
	voice_keysplit voicegroup223, KeySplitTable9     @ french horns
	voice_keysplit voicegroup224, KeySplitTable32    @ distortion guitar 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 224, 242, 101, 220
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_12, 224, 242, 101, 220
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass_c1_16, 255, 42, 255, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 219, 252, 196
	voice_keysplit voicegroup225, KeySplitTable23    @ upright bass 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 220
	voice_directsound 60, 0, DirectSoundWaveData_dp_oboe_c3_16, 255, 243, 127, 216
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 240, 242, 0, 182
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 58, 0, 101, 220
	voice_directsound 60, 0, DirectSoundWaveData_dp_sy_clarinet_c3_16, 255, 243, 159, 216
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 182
	voice_keysplit voicegroup226, KeySplitTable33    @ flute
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodpat_c4_16, 100, 247, 78, 136
	voice_directsound 60, 0, DirectSoundWaveData_dp_basschoir36, 255, 200, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 200, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 200, 255, 171
@	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 78, 196			@ remaining voices wrap around
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy		@ to the next voice group, so
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 200, 255, 171			@ have some dittos
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 200, 255, 171
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_keysplit voicegroup227, KeySplitTable25    @ music box (platinum only)
@	voice_keysplit voicegroup228, KeySplitTable34    @ banjo

	.align 2
voicegroup192:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 78, 196
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 200, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 200, 255, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_keysplit voicegroup227, KeySplitTable25    @ music box (platinum only)
	voice_keysplit voicegroup228, KeySplitTable34    @ banjo
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne1_roop, 255, 255, 191, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 255, 191, 32
	voice_directsound 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 255, 16
	voice_directsound 60, 64, DirectSoundWaveData_dp_bass2, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_808snare_16, 255, 220, 0, 64
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr2_16, 255, 0, 255, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1_16, 255, 0, 255, 171
	voice_directsound 61, 58, DirectSoundWaveData_dp_rim1_roop, 255, 220, 0, 16
	voice_directsound 60, 64, DirectSoundWaveData_dp_oct_snare_16, 255, 0, 255, 0
	voice_directsound 60, 70, DirectSoundWaveData_dp_053clap, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 226, 127, 0
	voice_directsound 29, 30, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 60, 80, DirectSoundWaveData_dp_closed_hihat_16, 255, 0, 227, 32
	voice_directsound 34, 40, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 60, 80, DirectSoundWaveData_dp_pedalhight, 255, 0, 235, 16
	voice_directsound 41, 50, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 60, 80, DirectSoundWaveData_dp_open_hihat_16, 255, 241, 0, 0
	voice_directsound 47, 100, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 53, 107, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 57, 64, DirectSoundWaveData_dp_cymbal1_16, 255, 246, 0, 214
	voice_directsound 55, 117, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 16
	voice_directsound 58, 30, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216
	voice_directsound 59, 20, DirectSoundWaveData_dp_china_cynbal, 255, 250, 0, 226
	voice_directsound 60, 30, DirectSoundWaveData_dp_ridecap, 255, 250, 0, 232
	voice_directsound 60, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 32
	voice_directsound 60, 84, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 226
	voice_directsound 60, 110, DirectSoundWaveData_dp_cawbell_16, 255, 0, 255, 176
	voice_directsound 60, 36, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound 61, 102, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound 60, 86, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216
	voice_directsound 60, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176
	voice_directsound 57, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176

	.align 2
voicegroup193:: @
	voice_directsound 60, 20, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound 60, 24, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 57, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 60, 26, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 26, DirectSoundWaveData_dp_cabassa_16, 255, 243, 127, 176
	voice_directsound 60, 100, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound 60, 98, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 63, 102, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 60, 25, DirectSoundWaveData_dp_india_per_16, 255, 0, 255, 16
	voice_directsound 60, 112, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 57, 100, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 55, 34, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 52, 22, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 59, 34, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 56, 90, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 54, 20, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 0
	voice_directsound 60, 107, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 0
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 200, 0, 0
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 249, 0, 196
	voice_directsound 60, 90, DirectSoundWaveData_dp_sheiker, 255, 243, 111, 64
	voice_directsound 60, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 70, 26, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 54, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 65, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 20, DirectSoundWaveData_dp_castanet_22, 255, 0, 255, 176
	voice_directsound 60, 20, DirectSoundWaveData_dp_kaaroop_16, 255, 255, 191, 238
	voice_directsound 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 255, 16
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr2_16, 255, 0, 255, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1_16, 255, 0, 255, 176
	voice_directsound 60, 64, DirectSoundWaveData_dp_oct_snare_16, 255, 0, 255, 0
	voice_directsound 60, 70, DirectSoundWaveData_dp_053clap, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 228, 127, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 32
	voice_directsound 60, 58, DirectSoundWaveData_dp_808snare_16, 255, 222, 0, 64
	voice_directsound 60, 64, DirectSoundWaveData_dp_bass2, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_rim1_roop, 255, 255, 191, 16
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne1_roop, 255, 255, 191, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 255, 191, 32
	voice_directsound 48, 30, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 60, 82, DirectSoundWaveData_dp_closehight_16, 255, 0, 227, 32
	voice_directsound 53, 40, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 60, 82, DirectSoundWaveData_dp_pedalhight, 255, 0, 227, 32
	voice_directsound 60, 50, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 60, 82, DirectSoundWaveData_dp_openhight, 254, 235, 0, 32
	voice_directsound 66, 90, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 72, 100, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 57, 64, DirectSoundWaveData_dp_cymbal1_16, 255, 247, 0, 216
	voice_directsound 74, 110, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 16
	voice_directsound 58, 30, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216

	.align 2
voicegroup194:: @
	voice_directsound 59, 20, DirectSoundWaveData_dp_china_cynbal, 255, 250, 0, 226
	voice_directsound 60, 30, DirectSoundWaveData_dp_ridecap, 255, 250, 0, 232
	voice_directsound 60, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 32
	voice_directsound 58, 84, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 226
	voice_directsound 60, 110, DirectSoundWaveData_dp_cawbell_16, 255, 0, 255, 176
	voice_directsound 60, 36, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound 61, 102, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound 60, 86, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216
	voice_directsound 60, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176
	voice_directsound 57, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176
	voice_directsound 60, 20, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound 60, 24, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 57, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 60, 26, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 26, DirectSoundWaveData_dp_cabassa_16, 255, 243, 127, 176
	voice_directsound 60, 100, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound 60, 98, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 63, 102, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 60, 25, DirectSoundWaveData_dp_india_per_16, 255, 0, 255, 16
	voice_directsound 60, 112, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 57, 100, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 55, 34, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 52, 22, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 59, 34, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 56, 90, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 57, 90, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 58, 90, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 200, 0, 0
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 249, 0, 196
	voice_directsound 60, 90, DirectSoundWaveData_dp_sheiker, 255, 243, 111, 64
	voice_directsound 60, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 61, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 62, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 63, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 60, 94, DirectSoundWaveData_dp_castanet_22, 255, 0, 255, 176
	voice_directsound 60, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 255, 171
	voice_directsound 61, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 255, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 0

	.align 2
voicegroup195:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_g1_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c2_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c3_16, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_g3_16, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c4_16, 255, 248, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_f4_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c5_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c6_16, 255, 247, 0, 208

	.align 2
voicegroup196:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c0_16, 255, 249, 0, 229
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c1_16, 255, 249, 0, 226

	.align 2
voicegroup197:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia_c3_22, 255, 243, 0, 32
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia_c4_22, 255, 243, 0, 32

	.align 2
voicegroup198:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia2_c3_22, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia2_c4_22, 255, 249, 0, 208

	.align 2
voicegroup199:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_clavi_c1_16, 255, 249, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_clavi_c2_16, 255, 249, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_clavi_c3_16, 255, 249, 0, 16

	.align 2
voicegroup200:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c1_16, 255, 247, 0, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c2_16, 255, 247, 0, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c3_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c4_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c5_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c6_16, 255, 247, 0, 208

	.align 2
voicegroup201:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_marin_c3_16, 255, 247, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_marin_c4_16, 255, 247, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_marin_c5_16, 255, 247, 0, 216

	.align 2
voicegroup202:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c2_16, 255, 249, 25, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c3_16, 255, 249, 25, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c4_16, 255, 249, 57, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c5_16, 255, 249, 57, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c6_16, 255, 247, 25, 196

	.align 2
voicegroup203:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_tub_bell_c3_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_tub_bell_c4_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_tub_bell_c5_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_tub_bell_c6_16, 255, 249, 0, 226

	.align 2
voicegroup204:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano36, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano48, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano60, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano72, 255, 248, 0, 208

	.align 2
voicegroup205:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c2_16, 255, 0, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c3_16, 255, 200, 227, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c4_16, 255, 0, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c5_16, 255, 0, 255, 208

	.align 2
voicegroup206:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_org4_c3_16, 255, 0, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org4_c4_16, 255, 0, 255, 208

	.align 2
voicegroup207:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c1_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c2_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c3_16, 100, 200, 217, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c4_16, 81, 200, 191, 196

	.align 2
voicegroup208:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e1_16, 255, 253, 127, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e2_16, 255, 253, 127, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e3_16, 255, 253, 127, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e4_16, 255, 253, 127, 208

	.align 2
voicegroup209:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_clean_gt_c1_16, 255, 247, 0, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_clean_gt_c2_16, 255, 247, 0, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_clean_gt_c3_16, 255, 247, 0, 176

	.align 2
voicegroup210:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e1_16, 255, 253, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_c2_16, 255, 253, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e3_16, 255, 253, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e4_16, 255, 253, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_b4_16, 255, 253, 0, 16

	.align 2
voicegroup211:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_power_gt_e1_16, 255, 251, 127, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_power_gt_b1_16, 255, 251, 127, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_power_gt_e2_16, 255, 251, 127, 16

	.align 2
voicegroup212:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_g1_16, 255, 251, 0, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_gs2_16, 255, 251, 0, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 251, 0, 176

	.align 2
voicegroup213:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c1_16, 100, 243, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c3_16, 100, 247, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c4_16, 67, 247, 118, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c5_16, 45, 247, 78, 208

	.align 2
voicegroup214:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_pic_g4_16, 255, 235, 159, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_pic_g5_16, 255, 228, 159, 188

	.align 2
voicegroup215:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_harp_c3_16, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_harp_c4_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_harp_c5_16, 255, 243, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_harp_c6_16, 255, 235, 0, 196

	.align 2
voicegroup216:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_e_16, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_as_16, 255, 248, 0, 205

	.align 2
voicegroup217:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c1_16, 255, 243, 227, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c2_16, 255, 240, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c3_16, 135, 235, 159, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c4_16, 135, 225, 127, 208

	.align 2
voicegroup218:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_merotim_c2_16, 255, 250, 0, 212
	voice_directsound 60, 0, DirectSoundWaveData_dp_merotim_c3_16, 255, 250, 0, 212

	.align 2
voicegroup219:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs3_16, 255, 243, 101, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs4_16, 255, 243, 101, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_b4_16, 255, 235, 101, 208

	.align 2
voicegroup220:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_trombone_c2_16, 255, 243, 159, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trombone_c3_16, 255, 243, 159, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trombone_c4_16, 255, 243, 159, 208

	.align 2
voicegroup221:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_tuba_c1_22, 255, 0, 252, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_tuba_c2_22, 255, 0, 252, 196

	.align 2
voicegroup222:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs3_16, 255, 243, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs4_16, 255, 243, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_b4_16, 255, 235, 191, 208

	.align 2
voicegroup223:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_f_horn_c2_16, 62, 219, 219, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_f_horn_c4_16, 255, 219, 255, 208

	.align 2
voicegroup224:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c1_16, 255, 247, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c2_16, 255, 247, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c3_16, 255, 247, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c4_16, 255, 247, 255, 176

	.align 2
voicegroup225:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_g1_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_gs2_16, 255, 0, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 0, 255, 176

	.align 2
voicegroup226:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c4_16, 255, 247, 159, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c5_16, 255, 247, 127, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c6_16, 255, 247, 71, 196

	.align 2
voicegroup227:: @
	voice_directsound 60, 0, DirectSoundWaveData_pl_musicbox62, 255, 250, 2, 236
	voice_directsound 60, 0, DirectSoundWaveData_pl_musicbox79, 255, 248, 2, 224

	.align 2
voicegroup228:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_banjo48, 255, 243, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_banjo60, 255, 243, 0, 208

	.align 2
voicegroup229:: @ HGSS main
	voice_keysplit voicegroup233, KeySplitTable35    @ piano
	voice_keysplit voicegroup234, KeySplitTable36    @ piano 2
	voice_keysplit voicegroup235, KeySplitTable37    @ piano octave
	voice_keysplit voicegroup236, KeySplitTable9     @ rhodes 1
	voice_keysplit voicegroup237, KeySplitTable9     @ rhodes 2
	voice_keysplit voicegroup238, KeySplitTable36    @ vibraphone
	voice_keysplit voicegroup239, KeySplitTable38    @ marimba
	voice_keysplit voicegroup240, KeySplitTable39    @ xylophone
	voice_keysplit voicegroup241, KeySplitTable25    @ tubular bell
	voice_keysplit voicegroup242, KeySplitTable36    @ glockenspiel
	voice_keysplit voicegroup243, KeySplitTable38    @ music box
	voice_keysplit voicegroup244, KeySplitTable40    @ drawbar organ
	voice_keysplit voicegroup245, KeySplitTable40    @ jazz organ
	voice_keysplit voicegroup246, KeySplitTable40    @ accordion
	voice_keysplit voicegroup247, KeySplitTable41    @ nylon guitar
	voice_keysplit voicegroup248, KeySplitTable41    @ martin guitar
	voice_keysplit voicegroup249, KeySplitTable32    @ distortion guitar 1
	voice_keysplit voicegroup250, KeySplitTable32    @ distortion guitar 2
	voice_keysplit voicegroup251, KeySplitTable41    @ clean guitar
	voice_keysplit voicegroup252, KeySplitTable42    @ upright bass
	voice_keysplit voicegroup253, KeySplitTable43    @ fingered bass
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 192
	voice_keysplit voicegroup254, KeySplitTable44    @ synth bass
	voice_keysplit voicegroup255, KeySplitTable45    @ strings
	voice_keysplit voicegroup256, KeySplitTable46    @ violin
	voice_keysplit voicegroup257, KeySplitTable47    @ cello
	voice_keysplit voicegroup258, KeySplitTable48    @ pizzicato
	voice_keysplit voicegroup259, KeySplitTable40    @ harp
	voice_keysplit voicegroup260, KeySplitTable40    @ timpani
	voice_keysplit voicegroup261, KeySplitTable39    @ trumpets
	voice_keysplit voicegroup262, KeySplitTable47    @ trombones
	voice_keysplit voicegroup263, KeySplitTable49    @ french horn solo
	voice_keysplit voicegroup264, KeySplitTable50    @ french horns
	voice_keysplit voicegroup265, KeySplitTable51    @ oboe
	voice_keysplit voicegroup266, KeySplitTable52    @ clarinet
	voice_keysplit voicegroup267, KeySplitTable53    @ flute
	voice_keysplit voicegroup268, KeySplitTable54    @ bassoon
	voice_keysplit voicegroup269, KeySplitTable55    @ orchestra hit
	voice_keysplit voicegroup270, KeySplitTable38    @ square wave
	voice_keysplit_all voicegroup230				 @ drums
	voice_keysplit_all voicegroup231				 @ taiko drums
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 251, 0, 171
	voice_keysplit voicegroup271, KeySplitTable56    @ koto
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 40, 211
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 67, 243, 155, 224
	voice_directsound 60, 0, DirectSoundWaveData_dp_explosion, 67, 255, 0, 245
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 250, 0, 171 @ 1 octave too low
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0  @ also 066 in BATTLE4 and DUNGEON4
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 252, 0, 96
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 250, 0, 220
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 220
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 192
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 42, 0, 57, 192
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 240, 242, 0, 192
@	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192	@ remaining voices wrap around
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16		@ to the next voice group, so
@	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 167, 235, 171		@ have some dittos
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_37, 80, 234, 191, 220
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_12, 80, 234, 191, 220
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 197, 255, 171						@ 60
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 197, 255, 171						@ 61
@	voice_keysplit_all voicegroup232				 @ synth kick+snare										@ 62
@	voice_keysplit voicegroup216, KeySplitTable27    @ DPPt timpani											@ 63
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 42, 255, 192						@ 64
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220						@ 65
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171						@ 66
@	voice_keysplit voicegroup272, KeySplitTable57    @ shamisen												@ 67
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hyoshigi, 255, 0, 255, 171								@ 68
@	voice_directsound 60, 0, DirectSoundWaveData_hg_kodaiko, 255, 0, 255, 171								@ 69
@	voice_directsound 60, 0, DirectSoundWaveData_hg_tsuzumi, 255, 0, 255, 171								@ 70
@	voice_directsound 60, 0, DirectSoundWaveData_hg_jinglebell, 255, 0, 255, 171							@ 71
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hoohclap, 255, 0, 255, 0								@ 72
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171						@ 73
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 197, 255, 171						@ 74
@	voice_directsound 60, 0, DirectSoundWaveData_hg_choirc5, 255, 197, 255, 171 @ 1 octave too low			@ 75
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 197, 255, 171 @ 1 octave too high	@ 76
@	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32						@ 77
@	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192						@ 78
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 171							@ 79
@	voice_keysplit voicegroup273, KeySplitTable58    @ piano (national park)								@ 80
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32								@ 81
@	voice_keysplit voicegroup219, KeySplitTable29    @ dp trumpets (arceus)									@ 82
@	voice_keysplit voicegroup220, KeySplitTable30    @ dp trombone (arceus)									@ 83

	.align 2
voicegroup230:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 167, 235, 171
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_37, 80, 234, 191, 220
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_12, 80, 234, 191, 220
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 197, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 197, 255, 171
	voice_keysplit_all voicegroup232				 @ synth kick+snare
	voice_keysplit voicegroup216, KeySplitTable27    @ DPPt timpani
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 42, 255, 192
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171
	voice_keysplit voicegroup272, KeySplitTable57    @ shamisen
	voice_directsound 60, 0, DirectSoundWaveData_hg_hyoshigi, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_kodaiko, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_tsuzumi, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_jinglebell, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_hoohclap, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 197, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_choirc5, 255, 197, 255, 171 @ 1 octave too low
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 197, 255, 171 @ 1 octave too high
	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192
	voice_directsound 60, 0, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 171
	voice_keysplit voicegroup273, KeySplitTable58    @ piano (national park)
	voice_directsound 60, 0, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_keysplit voicegroup219, KeySplitTable29    @ dp trumpets (arceus)
	voice_keysplit voicegroup220, KeySplitTable30    @ dp trombone (arceus)
	voice_directsound 60, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 255, 191, 171
	voice_directsound 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_bass2, 255, 0, 227, 171
	voice_directsound 61, 64, DirectSoundWaveData_dp_bass2, 255, 0, 227, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_808snare_16, 255, 220, 0, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr2_16, 255, 0, 255, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 171
	voice_directsound 61, 58, DirectSoundWaveData_dp_rim1_roop, 255, 220, 0, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_oct_snare_16, 255, 0, 255, 171
	voice_directsound 60, 70, DirectSoundWaveData_dp_053clap, 255, 0, 227, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 226, 127, 171
	voice_directsound 60, 30, DirectSoundWaveData_hg_135tom, 255, 0, 255, 171
	voice_directsound 60, 80, DirectSoundWaveData_hg_062chh, 255, 242, 0, 171
	voice_directsound 60, 40, DirectSoundWaveData_hg_137tom, 255, 0, 255, 171
	voice_directsound 61, 40, DirectSoundWaveData_hg_137tom, 255, 0, 255, 171
	voice_directsound 60, 50, DirectSoundWaveData_hg_138tom, 255, 0, 255, 171
	voice_directsound 60, 80, DirectSoundWaveData_hg_063ohh, 255, 241, 0, 171
	voice_directsound 60, 100, DirectSoundWaveData_hg_136tom, 255, 0, 255, 171
	voice_directsound 60, 64, DirectSoundWaveData_hg_033orccym, 255, 246, 0, 214
	voice_directsound 57, 64, DirectSoundWaveData_hg_032crash, 255, 242, 0, 214
	voice_directsound 58, 64, DirectSoundWaveData_hg_032crash, 255, 242, 0, 214
	voice_directsound 59, 64, DirectSoundWaveData_hg_032crash, 255, 242, 0, 214
	voice_directsound 59, 20, DirectSoundWaveData_hg_022china, 255, 250, 0, 224
	voice_directsound 60, 30, DirectSoundWaveData_dp_ridecap, 255, 250, 0, 210
	voice_directsound 60, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171
	voice_directsound 60, 84, DirectSoundWaveData_hg_114splash, 255, 250, 0, 171
	voice_directsound 60, 110, DirectSoundWaveData_hg_031cowbl, 255, 0, 255, 171
	voice_directsound 60, 36, DirectSoundWaveData_hg_032crash, 255, 248, 0, 214
	voice_directsound 61, 102, DirectSoundWaveData_hg_032crash, 255, 248, 0, 214
	voice_directsound 60, 86, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 214
	voice_directsound 60, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 171
	voice_directsound 57, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 171
	voice_directsound 60, 20, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 171
	voice_directsound 60, 24, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 57, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 58, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 59, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 60, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 60, 105, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 171
	voice_directsound 60, 105, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171

	.align 2
voicegroup231:: @
	voice_directsound 63, 105, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 64, 105, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 65, 105, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 66, 105, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 67, 105, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 68, 105, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 60, 20, DirectSoundWaveData_dp_sheiker, 255, 242, 127, 171
	voice_directsound 61, 20, DirectSoundWaveData_dp_sheiker, 255, 242, 127, 171
	voice_directsound 60, 105, DirectSoundWaveData_dp_sheiker, 255, 242, 127, 171
	voice_directsound 61, 105, DirectSoundWaveData_dp_sheiker, 255, 242, 127, 171
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 197, 0, 32
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 248, 0, 192
	voice_directsound 24, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 25, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 26, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 27, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 28, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 29, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 30, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 31, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 32, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 33, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 34, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 35, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 36, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 37, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 38, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 39, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 40, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 41, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 42, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 43, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 44, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 45, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 46, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 47, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 48, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 49, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 50, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 51, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 52, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 53, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 54, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 55, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 56, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 57, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 58, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 59, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 60, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 61, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 62, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 63, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 64, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 65, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 66, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 67, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 68, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 69, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 70, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 71, 40, DirectSoundWaveData_hg_128jdruml, 255, 0, 227, 171
	voice_directsound 60, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 61, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 62, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 63, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 64, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 65, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 66, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 67, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 68, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 69, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 70, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 71, 40, DirectSoundWaveData_hg_129jdrumm, 255, 0, 227, 171
	voice_directsound 60, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 61, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 62, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 63, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 64, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 65, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 66, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 67, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 68, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 69, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 70, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 71, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 72, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 73, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 74, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 75, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 76, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 77, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 78, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 79, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171

	.align 2
voicegroup232:: @
	voice_directsound 80, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 81, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 82, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 83, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 84, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 85, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 86, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 87, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 88, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 89, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 90, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 91, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 92, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 93, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 94, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 95, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 96, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 97, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 98, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 99, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 100, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 101, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 102, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 103, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 104, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 105, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 106, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 107, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 108, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 109, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 110, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 111, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 112, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 113, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 114, 40, DirectSoundWaveData_hg_130jdrumh, 255, 0, 227, 171
	voice_directsound 127, 64, DirectSoundWaveData_dp_clean_gt_c3_16, 255, 246, 0, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 255, 171
	voice_directsound 61, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 255, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 171

	.align 2
voicegroup233:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_051pnoc2, 255, 249, 0, 224
	voice_directsound 60, 0, DirectSoundWaveData_hg_052pnoc3, 255, 249, 0, 224
	voice_directsound 60, 0, DirectSoundWaveData_hg_053pnoc4, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_054pnoc5, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_055pnoc6, 255, 247, 0, 205

	.align 2
voicegroup234:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_005pnoffc4, 255, 249, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_006pnoffc5, 255, 249, 0, 171

	.align 2
voicegroup235:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_082octpnoc2, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_083octpnoc3, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_084octpnoc4, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_085octpnoc5, 255, 249, 0, 205

	.align 2
voicegroup236:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_043rhodc4, 255, 250, 0, 210
	voice_directsound 60, 0, DirectSoundWaveData_hg_044rhodc5, 255, 250, 0, 210

	.align 2
voicegroup237:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_043rhodc4, 255, 250, 0, 32
	voice_directsound 60, 0, DirectSoundWaveData_hg_044rhodc5, 255, 250, 0, 32

	.align 2
voicegroup238:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_148vibrc4, 255, 246, 0, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_149vibrc5, 255, 246, 0, 205

	.align 2
voicegroup239:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_068marimc4, 255, 246, 0, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_069marimc5, 255, 246, 0, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_070marimc6, 255, 246, 0, 214

	.align 2
voicegroup240:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_156xylo1c4, 255, 248, 25, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_155xylo1a4, 255, 248, 25, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_157xylo1f5, 255, 248, 57, 192

	.align 2
voicegroup241:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_147tbellg4, 255, 248, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_146tbellc5, 255, 248, 25, 205

	.align 2
voicegroup242:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_049glocknc4, 255, 248, 2, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_050glocknc5, 255, 248, 2, 205

	.align 2
voicegroup243:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_071musboxc4, 255, 246, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_072musboxc5, 255, 246, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_073musboxc6, 255, 246, 0, 205

	.align 2
voicegroup244:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_038drawbc3, 255, 197, 227, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_039drawbc4, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_040drawbc5, 255, 0, 255, 205

	.align 2
voicegroup245:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_091jazorgc3, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_092jazorgc4, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_093jazorgc5, 255, 0, 255, 205

	.align 2
voicegroup246:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_002accorc3, 255, 0, 217, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_003accorc4, 255, 0, 217, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_004accorc5, 254, 197, 217, 192

	.align 2
voicegroup247:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_077nylong2, 255, 251, 6, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_078nylong3, 255, 251, 6, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_076nylone4, 255, 251, 6, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_075nylonc5, 255, 251, 6, 205

	.align 2
voicegroup248:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_117marting2, 255, 251, 14, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_118marting3, 255, 251, 14, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_116martine4, 255, 251, 14, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_115martinc5, 255, 251, 14, 192

	.align 2
voicegroup249:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e1_16, 255, 253, 0, 32
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_c2_16, 255, 253, 0, 32
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e3_16, 255, 253, 0, 32
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e4_16, 255, 253, 0, 32

	.align 2
voicegroup250:: @
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e1_16, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_c2_16, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e3_16, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e4_16, 255, 253, 0, 171

	.align 2
voicegroup251:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_029cleang2, 255, 246, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_030cleang3, 255, 246, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_028cleane4, 255, 246, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_027cleanc5, 255, 246, 0, 171

	.align 2
voicegroup252:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_000uprigc2, 255, 251, 0, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_001uprigc3, 255, 251, 0, 192

	.align 2
voicegroup253:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_041ampega2, 255, 234, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_042ampega3, 255, 234, 159, 192

	.align 2
voicegroup254:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_123elastkc2, 255, 42, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_124elastkc3, 255, 42, 227, 171

	.align 2
voicegroup255:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_120str1c4, 255, 242, 191, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_119str1a4, 255, 242, 191, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_122str1f5, 254, 242, 191, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_121str1c6, 254, 242, 191, 192

	.align 2
voicegroup256:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_152violne4, 254, 242, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_151violnc5, 254, 246, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_150violna5, 254, 246, 255, 205

	.align 2
voicegroup257:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_021cellog2, 254, 242, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_020celloe3, 254, 246, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_019celloc4, 254, 246, 255, 205

	.align 2
voicegroup258:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_102pizzg2, 255, 242, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_100pizze3, 255, 242, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_099pizzc4, 255, 242, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_098pizza4, 255, 242, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_101pizzf5, 255, 239, 25, 205

	.align 2
voicegroup259:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_058harpc3, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_059harpc4, 255, 246, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_060harpc5, 255, 242, 0, 205

	.align 2
voicegroup260:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_133timpg3, 255, 251, 25, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_132timpc4, 255, 251, 25, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_134timpg4, 255, 251, 25, 192

	.align 2
voicegroup261:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_144tptc4, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_143tpta4, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_145tptg5, 255, 234, 191, 205

	.align 2
voicegroup262:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_142tbng2, 255, 242, 159, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_141tbne3, 255, 242, 159, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_140tbnc4, 255, 242, 159, 205

	.align 2
voicegroup263:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_016fhsolof3, 255, 0, 252, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_015fhsolod4, 255, 0, 252, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_014fhsolob4, 255, 0, 252, 192

	.align 2
voicegroup264:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_048fhnsf3, 255, 216, 219, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_047fhnsd4, 255, 216, 219, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_046fhnsb4, 255, 216, 255, 205

	.align 2
voicegroup265:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_081oboee4, 255, 242, 191, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_080oboec5, 255, 242, 191, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_079oboea5, 255, 242, 191, 214

	.align 2
voicegroup266:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_025clarig3, 255, 242, 127, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_024clarie4, 255, 242, 127, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_023claric5, 255, 242, 127, 214

	.align 2
voicegroup267:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_095flt1c4, 255, 246, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_094flt1a4, 255, 246, 127, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_097flt1f5, 255, 246, 127, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_096flt1c6, 255, 246, 78, 192

	.align 2
voicegroup268:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_012bsne2, 255, 242, 127, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_011bsnc3, 255, 242, 127, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_010bsna3, 255, 242, 127, 214

	.align 2
voicegroup269:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_086orchitc4, 255, 248, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_087orchitc5, 255, 248, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_089orchitg5, 255, 248, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_088orchitc6, 255, 248, 25, 205

	.align 2
voicegroup270:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_125squarc4, 255, 242, 191, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_126squarc5, 255, 242, 191, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_127squarc6, 255, 234, 191, 171

	.align 2
voicegroup271:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_067kotoe3, 255, 246, 0, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_066kotoc4, 255, 246, 0, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_065kotoa4, 255, 246, 0, 192

	.align 2
voicegroup272:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_shamisend3, 255, 250, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_shamisenas3, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_shamiseng4, 255, 247, 0, 205

	.align 2
voicegroup273:: @
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4c2, 255, 249, 0, 224
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4a2, 255, 249, 0, 224
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4f3, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4d4, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4b4, 255, 247, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4g5, 255, 247, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4e6, 255, 247, 0, 205
