#ifndef GUARD_CONSTANTS_MENU_H
#define GUARD_CONSTANTS_MENU_H

enum ScrollMulti
{
    LISTMENU_BADGES,
    LISTMENU_SILPHCO_FLOORS,
    LISTMENU_ROCKET_HIDEOUT_FLOORS,
    LISTMENU_DEPT_STORE_FLOORS,
    LISTMENU_WIRELESS_LECTURE_HEADERS,
    LISTMENU_BERRY_POWDER,
    LISTMENU_TRAINER_TOWER_FLOORS,
    SCROLL_MULTI_BF_RECEPTIONIST,
    SCROLL_MULTI_BF_MOVE_TUTOR_1,
    SCROLL_MULTI_BF_MOVE_TUTOR_2,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_1,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_2,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_VITAMIN_VENDOR,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_HOLD_ITEM_VENDOR,
    SCROLL_MULTI_NONE = 99,
};

#define MAX_SCROLL_MULTI_ON_SCREEN 6
#define MAX_SCROLL_MULTI_LENGTH 16

// Std String Ids
#define STDSTRING_COOL              0
#define STDSTRING_BEAUTY            1
#define STDSTRING_CUTE              2
#define STDSTRING_SMART             3
#define STDSTRING_TOUGH             4
#define STDSTRING_COOL2             5
#define STDSTRING_BEAUTY2           6
#define STDSTRING_CUTE2             7
#define STDSTRING_SMART2            8
#define STDSTRING_TOUGH2            9
#define STDSTRING_ITEMS             10
#define STDSTRING_KEY_ITEMS         11
#define STDSTRING_POKEBALLS         12
#define STDSTRING_TMHMS             13
#define STDSTRING_BERRIES           14
#define STDSTRING_BOULDER_BADGE     15
#define STDSTRING_CASCADE_BADGE     16
#define STDSTRING_THUNDER_BADGE     17
#define STDSTRING_RAINBOW_BADGE     18
#define STDSTRING_SOUL_BADGE        19
#define STDSTRING_MARSH_BADGE       20
#define STDSTRING_VOLCANO_BADGE     21
#define STDSTRING_EARTH_BADGE       22
#define STDSTRING_COINS             23
#define STDSTRING_ITEMS_POCKET      24
#define STDSTRING_KEY_ITEMS_POCKET  25
#define STDSTRING_POKEBALLS_POCKET  26
#define STDSTRING_TM_CASE           27
#define STDSTRING_BERRY_POUCH       28
#define STDSTRING_SINGLE            29
#define STDSTRING_DOUBLE            30
#define STDSTRING_MULTI             31
#define STDSTRING_MULTI_LINK        32
#define STDSTRING_BATTLE_DOME       33
#define STDSTRING_BATTLE_FACTORY    34
#define STDSTRING_BATTLE_PALACE     35
#define STDSTRING_BATTLE_ARENA      36
#define STDSTRING_BATTLE_PIKE       37
#define STDSTRING_BATTLE_PYRAMID    38

#endif //GUARD_CONSTANTS_MENU_H
