#ifndef GUARD_CONSTANTS_QUEST_LOG_H
#define GUARD_CONSTANTS_QUEST_LOG_H

// Layout of Quest Log script commands
#define QL_CMD_EVENT_MASK  0x0FFF
#define QL_CMD_COUNT_SHIFT 12
#define QL_CMD_COUNT_MASK  (0xF << QL_CMD_COUNT_SHIFT)

#define QL_IS_PLAYBACK_STATE (gQuestLogState == QL_STATE_PLAYBACK || gQuestLogState == QL_STATE_PLAYBACK_LAST)

// Parameter to QuestLog_OnEscalatorWarp
enum QLEscalatorType
{
    QL_ESCALATOR_OUT = 1,
    QL_ESCALATOR_IN,
};

enum QLState
{
    QL_STATE_NONE,
    QL_STATE_RECORDING,
    QL_STATE_PLAYBACK,
    QL_STATE_PLAYBACK_LAST,
};

enum QLPlaybackState
{
    QL_PLAYBACK_STATE_STOPPED,
    QL_PLAYBACK_STATE_RUNNING,
    QL_PLAYBACK_STATE_RECORDING,
    QL_PLAYBACK_STATE_ACTION_END,
    QL_PLAYBACK_STATE_RECORDING_NO_DELAY,
};

enum QLStartType
{
    QL_START_NORMAL = 1,
    QL_START_WARP,
};

// gGlobalFieldTintMode
enum QLTintMode
{
    QL_TINT_NONE,
    QL_TINT_GRAYSCALE,
    QL_TINT_SEPIA,
    QL_TINT_BACKUP_GRAYSCALE,
};

enum QLEvent
{
    QL_EVENT_INPUT,                           // Null
    QL_EVENT_GFX_CHANGE,                      // Null
    QL_EVENT_MOVEMENT,                        // Null
    QL_EVENT_SWITCHED_PARTY_ORDER,
    QL_EVENT_USED_ITEM,
    QL_EVENT_GAVE_HELD_ITEM,
    QL_EVENT_GAVE_HELD_ITEM_BAG,
    QL_EVENT_GAVE_HELD_ITEM_PC,
    QL_EVENT_TOOK_HELD_ITEM,
    QL_EVENT_SWAPPED_HELD_ITEM,
    QL_EVENT_SWAPPED_HELD_ITEM_PC,
    QL_EVENT_USED_PKMN_CENTER,
    QL_EVENT_LINK_TRADED,
    QL_EVENT_LINK_BATTLED_SINGLE,
    QL_EVENT_LINK_BATTLED_DOUBLE,
    QL_EVENT_LINK_BATTLED_MULTI,
    QL_EVENT_USED_UNION_ROOM,
    QL_EVENT_USED_UNION_ROOM_CHAT,
    QL_EVENT_LINK_TRADED_UNION,
    QL_EVENT_LINK_BATTLED_UNION,
    QL_EVENT_SWITCHED_MONS_BETWEEN_BOXES,
    QL_EVENT_SWITCHED_MONS_WITHIN_BOX,
    QL_EVENT_SWITCHED_PARTY_MON_FOR_PC_MON,
    QL_EVENT_MOVED_MON_BETWEEN_BOXES,
    QL_EVENT_MOVED_MON_WITHIN_BOX,
    QL_EVENT_WITHDREW_MON_PC,
    QL_EVENT_DEPOSITED_MON_PC,
    QL_EVENT_SWITCHED_MULTIPLE_MONS,
    QL_EVENT_DEPOSITED_ITEM_PC,
    QL_EVENT_WITHDREW_ITEM_PC,
    QL_EVENT_DEFEATED_GYM_LEADER,
    QL_EVENT_DEFEATED_WILD_MON,
    QL_EVENT_DEFEATED_E4_MEMBER,
    QL_EVENT_DEFEATED_CHAMPION,
    QL_EVENT_DEFEATED_TRAINER,
    QL_EVENT_DEPARTED,
    QL_EVENT_USED_FIELD_MOVE,
    QL_EVENT_BOUGHT_ITEM,
    QL_EVENT_SOLD_ITEM,
    QL_EVENT_SCENE_END,                       // Null
    QL_EVENT_OBTAINED_STORY_ITEM,
    QL_EVENT_WAIT,                            // Null
    QL_EVENT_ARRIVED,
};

#define QL_EVENT_USED_POKEMART (QL_EVENT_BOUGHT_ITEM - 1) // Used as a start pos for QL_EVENT_BOUGHT_ITEM / QL_EVENT_SOLD_ITEM

#define IS_LINK_QL_EVENT(event)((event) >= QL_EVENT_LINK_TRADED && (event) <= QL_EVENT_LINK_BATTLED_UNION)
#define IS_VALID_QL_EVENT(event)((event) >= QL_EVENT_SWITCHED_PARTY_ORDER && (event) <= QL_EVENT_ARRIVED)

enum QLLocation
{
    QL_LOCATION_HOME,
    QL_LOCATION_OAKS_LAB,
    QL_LOCATION_VIRIDIAN_GYM,
    QL_LOCATION_LEAGUE_GATE_1,
    QL_LOCATION_LEAGUE_GATE_2,
    QL_LOCATION_VIRIDIAN_FOREST_1,
    QL_LOCATION_VIRIDIAN_FOREST_2,
    QL_LOCATION_PEWTER_MUSEUM,
    QL_LOCATION_PEWTER_GYM,
    QL_LOCATION_MT_MOON_1,
    QL_LOCATION_MT_MOON_2,
    QL_LOCATION_CERULEAN_GYM,
    QL_LOCATION_BIKE_SHOP,
    QL_LOCATION_BILLS_HOUSE,
    QL_LOCATION_DAY_CARE,
    QL_LOCATION_UNDERGROUND_PATH_1,
    QL_LOCATION_UNDERGROUND_PATH_2,
    QL_LOCATION_PKMN_FAN_CLUB,
    QL_LOCATION_VERMILION_GYM,
    QL_LOCATION_SS_ANNE,
    QL_LOCATION_DIGLETTS_CAVE_1,
    QL_LOCATION_DIGLETTS_CAVE_2,
    QL_LOCATION_ROCK_TUNNEL_1,
    QL_LOCATION_ROCK_TUNNEL_2,
    QL_LOCATION_POWER_PLANT,
    QL_LOCATION_PKMN_TOWER,
    QL_LOCATION_VOLUNTEER_HOUSE,
    QL_LOCATION_NAME_RATERS_HOUSE,
    QL_LOCATION_UNDERGROUND_PATH_3,
    QL_LOCATION_UNDERGROUND_PATH_4,
    QL_LOCATION_CELADON_DEPT_STORE,
    QL_LOCATION_CELADON_MANSION,
    QL_LOCATION_GAME_CORNER,
    QL_LOCATION_CELADON_GYM,
    QL_LOCATION_CELADON_RESTAURANT,
    QL_LOCATION_ROCKET_HIDEOUT,
    QL_LOCATION_SAFARI_ZONE,
    QL_LOCATION_FUCHSIA_GYM,
    QL_LOCATION_WARDENS_HOME,
    QL_LOCATION_FIGHTING_DOJO,
    QL_LOCATION_SAFFRON_GYM,
    QL_LOCATION_SILPH_CO,
    QL_LOCATION_SEAFOAM_ISLANDS_1,
    QL_LOCATION_SEAFOAM_ISLANDS_2,
    QL_LOCATION_PKMN_MANSION,
    QL_LOCATION_CINNABAR_GYM,
    QL_LOCATION_CINNABAR_LAB,
    QL_LOCATION_VICTORY_ROAD_1,
    QL_LOCATION_VICTORY_ROAD_2,
    QL_LOCATION_PKMN_LEAGUE,
    QL_LOCATION_CERULEAN_CAVE,
};

enum QLDepartedType
{
    QL_DEPARTED_TOWN_BUILDING,
    QL_DEPARTED_MUSEUM,
    QL_DEPARTED_GAME_CORNER,
    QL_DEPARTED_HOME,
    QL_DEPARTED_OAKS_LAB,
    QL_DEPARTED_GYM,
    QL_DEPARTED_SAFARI_ZONE,
    QL_DEPARTED_CAVE,
    QL_DEPARTED_MISC_BUILDING_1,
    QL_DEPARTED_MISC_BUILDING_2,
};

enum QLInput
{
    QL_INPUT_OFF,
    QL_INPUT_UP,
    QL_INPUT_DOWN,
    QL_INPUT_LEFT,
    QL_INPUT_RIGHT,
    QL_INPUT_L,
    QL_INPUT_R,
    QL_INPUT_START,
    QL_INPUT_SELECT,
    QL_INPUT_A,
    QL_INPUT_B,
};

enum QLActionType
{
    QL_ACTION_MOVEMENT,
    QL_ACTION_GFX_CHANGE,
    QL_ACTION_INPUT,
    QL_ACTION_EMPTY,
    QL_ACTION_WAIT = 254,
    QL_ACTION_SCENE_END = 255,
};

#endif //GUARD_CONSTANTS_QUEST_LOG_H
