#ifndef GUARD_CONSTANTS_SEAGALLOP_H
#define GUARD_CONSTANTS_SEAGALLOP_H

enum SeagallopLocation
{
    SEAGALLOP_VERMILION_CITY,
    SEAGALLOP_ONE_ISLAND,
    SEAGALLOP_TWO_ISLAND,
    SEAGALLOP_THREE_ISLAND,
    SEAGALLOP_FOUR_ISLAND,
    SEAGALLOP_FIVE_ISLAND,
    SEAGALLOP_SIX_ISLAND,
    SEAGALLOP_SEVEN_ISLAND,
    SEAGALLOP_CINNABAR_ISLAND,
    SEAGALLOP_NAVEL_ROCK,
    SEAGALLOP_BIRTH_ISLAND,
    SEAGALLOP_BATTLE_FRONTIER,
};

#define SEAGALLOP_MORE           254

#endif //GUARD_CONSTANTS_SEAGALLOP_H
