#ifndef GUARD_CONSTANTS_SHOP_H
#define GUARD_CONSTANTS_SHOP_H

enum ShopId
{
    SHOP_ID_VIRIDIAN_CITY_MART,
    SHOP_ID_PEWTER_CITY_MART,
    SHOP_ID_CERULEAN_CITY_MART,
    SHOP_ID_VERMILION_CITY_MART,
    SHOP_ID_LAVENDER_TOWN_MART,
    SHOP_ID_CELADON_CITY_DEPARTMENT_STORE_2F_ITEMS,
    SHOP_ID_CELADON_CITY_DEPARTMENT_STORE_2F_TMS,
    SHOP_ID_CELADON_CITY_DEPARTMENT_STORE_4F_ITEMS,
    SHOP_ID_CELADON_CITY_DEPARTMENT_STORE_5F_XITEMS,
    SHOP_ID_CELADON_CITY_DEPARTMENT_STORE_5F_VITAMINS,
    SHOP_ID_FUCHSIA_CITY_MART,
    SHOP_ID_SAFFRON_CITY_MART,
    SHOP_ID_CINNABAR_ISLAND_MART,
    SHOP_ID_INDIGO_PLATEAU_POKEMON_CENTER_1F,
    SHOP_ID_TWO_ISLAND_SHOP,
    SHOP_ID_THREE_ISLAND_MART,
    SHOP_ID_FOUR_ISLAND_MART,
    SHOP_ID_SIX_ISLAND_MART,
    SHOP_ID_SEVEN_ISLAND_MART,
    SHOP_ID_TRAINER_TOWER_LOBBY,
    SHOP_ID_BATTLE_FRONTIER_MART,
    SHOP_ID_COUNT,
};

#endif // GUARD_CONSTANTS_SHOP_H
